name: Bao component base workflow

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:

  gitlint:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git config --global --add safe.directory $(realpath .)
      - if: ${{ github.event_name == 'pull_request' }}
        run: gitlint --commits ${{ github.event.pull_request.base.sha }}..
      - if: ${{ github.event_name == 'push' }}
        run: gitlint --commits ${{ github.event.before }}..
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        run: gitlint --commits HEAD


  spell-check:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - run: |
          git config --global --add safe.directory $(realpath .)
          make spelling

  docformat:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - run: make rst-format

  build:
    runs-on: ubuntu-latest
    container: baoproject/bao:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - run: make html
